version: '3'
services:
    chattomey-api:
        depends_on:
            - pocketbase
        build:
            dockerfile: Dockerfile.api
        ports:
            - 5000:5000
        environment:
            - POCKETBASE_URL=http://pocketbase:8090

    pocketbase:
        container_name: pocketbase
        build:
            dockerfile: Dockerfile.pb
        image: pocketbase:latest
        ports:
            - 8090:8090
        volumes:
            - pocketbase-volume:/usr/local/bin/pb_data

volumes:
    pocketbase-volume:
